### ISSUE TITLE
How to connect my own DB to auth system in you chat service project? And where put my database credentials in project?

### ISSUE THREAD

**Issue by THRUWOL** [keyldev/blazoruitest#2]
I youse you chat system but i can't to connect my own db to project because idk where i can put my credential and change ports or specify db type

**Comment by keyldev** [comment]
Here https://github.com/keyldev/blazoruitest/blob/server-chat/BlazorUI/appsettings.json you can see the ConnectionStrings property. For now, it's bound for the MySQL default string connection as provider.

Well, if you want to change this info, or add the one more DB Provider you need:
1. Create a new connection, such as "DefaultConnection", for example, "PostgreConnection", insert the credentials, like host, user, db, password
2. Add from NuGet packages tool for supporting Postgre Provider, for example, Npgsql.EntityFrameworkCore.PostgreSQL
3. Go to Program.cs (https://github.com/keyldev/blazoruitest/blob/server-chat/BlazorUI/Program.cs) and change the 29 line options method to options._**UseYourProviderName**_, for example, options.UseNpgsql(builder.Configuration.GetConnectionString("PostgreConnection")
4. Add migration for your DB Instance via NuGet CLI (Консоль диспетчера пакетов): Add-Migration Postgre; Update-Database

**Comment by THRUWOL** [comment]
> Here https://github.com/keyldev/blazoruitest/blob/server-chat/BlazorUI/appsettings.json you can see the ConnectionStrings property. For now, it's bound for the MySQL default string connection as provider.
> 
> Well, if you want to change this info, or add the one more DB Provider you need:
> 
> 1. Create a new connection, such as "DefaultConnection", for example, "PostgreConnection", insert the credentials, like host, user, db, password
> 2. Add from NuGet packages tool for supporting Postgre Provider, for example, Npgsql.EntityFrameworkCore.PostgreSQL
> 3. Go to Program.cs (https://github.com/keyldev/blazoruitest/blob/server-chat/BlazorUI/Program.cs) and change the 29 line options method to options._**UseYourProviderName**_, for example, options.UseNpgsql(builder.Configuration.GetConnectionString("PostgreConnection")
> 4. Add migration for your DB Instance via NuGet CLI (Консоль диспетчера пакетов): Add-Migration Postgre; Update-Database

thanks
